language:
  java

test:
  adapter: mysql2
  database: CampingTest
  username: root
  encoding: utf8

before_install:
  mysql -e "CREATE DATABASE IF NOT EXISTS CampingTest; CREATE USER IF NOT EXISTS camping IDENTIFIED BY 'camping'; GRANT ALL PRIVILEGES ON CampingTest.* TO 'camping'@'%';"

